name: DBIx-ReportBuilder
version: 0.00_15
abstract: Interactive SQL report generator
author: Autrijus Tang (autrijus@autrijus.org)
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  DBIx::SearchBuilder: 0.90
  XML::Twig: 3.00
  GD::Graph: 0.01
  GD::Graph3d: 0.61
  Chart::Math::Axis: 0.1
  MIME::Base64: 2.12
  Image::Size: 0.01
no_index:
  directory:
    - inc
private:
  directory:
    - inc
generated_by: Module::Install version 0.27
