name: DBIx-ReportBuilder
module_name: DBIx::ReportBuilder
version: 0.00_03
abstract: Interactive SQL report generator
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
build_requires:
  Test::More: 0
requires:
  XML::Twig: 3.00
  DBIx::SearchBuilder: 0.90
private:
  directory:
    - inc
generated_by: Module::Install version 0.24
